CREATE DATABASE crud;

USE crud;

CREATE TABLE accounts (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    company VARCHAR(255) NULL,
    position VARCHAR(255) NULL,
    phone1 VARCHAR(20) NULL,
    phone2 VARCHAR(20) NULL,
    phone3 VARCHAR(20) NULL,
    PRIMARY KEY(id)
);